MYSQL_HOST=${cloud_nextcloud_db_host}
MYSQL_DATABASE=${cloud_nextcloud_db_name}
MYSQL_USER=${cloud_nextcloud_db_user}
MYSQL_PASSWORD=${cloud_nextcloud_db_password}
REDIS_HOST=${cloud_nextcloud_db_host}
REDIS_HOST_USER=nextcloud
#REDIS_DB_INDEX=0 - not supported yet
REDIS_HOST_PASSWORD=${cloud_nextcloud_redis_password}
NEXTCLOUD_ADMIN_USER=admin
NEXTCLOUD_ADMIN_PASSWORD=${cloud_nextcloud_admin_password}
APACHE_DISABLE_REWRITE_IP=1
TRUSTED_PROXIES=${cloud_nextcloud_trusted_proxies}
NEXTCLOUD_TRUSTED_DOMAINS=${cloud_nextcloud_trusted_domains}
