version: '3'

volumes:
  prowlarr-config:
  sonarr-config:
  radarr-config:
  bazarr-config:
  jellyseerr-config:

services:
  # Torrent tracker index management
  prowlarr:
    image: docker.io/linuxserver/prowlarr:2.4.0
    restart: unless-stopped
    network_mode: pasta
    ports:
      - 9696:9696    # web UI
    volumes:
      - prowlarr-config:/config
    userns_mode: keep-id
    environment:
      TZ: Etc/UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/ping"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # TvShow management
  sonarr:
    image: docker.io/linuxserver/sonarr:4.0.19
    restart: unless-stopped
    network_mode: pasta
    ports:
      - 8989:8989    # web UI
    volumes:
      - sonarr-config:/config
      - /srv:/srv
    userns_mode: keep-id
    environment:
      TZ: Etc/UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/ping"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # Movie management
  radarr:
    image: docker.io/linuxserver/radarr:6.2.1
    restart: unless-stopped
    network_mode: pasta
    ports:
      - 7878:7878    # web UI
    volumes:
      - radarr-config:/config
      - /srv:/srv
    userns_mode: keep-id
    environment:
      TZ: Etc/UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/ping"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # Subtitle management
  bazarr:
    image: docker.io/linuxserver/bazarr:1.5.6
    restart: unless-stopped
    network_mode: pasta
    ports:
      - 6767:6767    # web UI
    volumes:
      - bazarr-config:/config
      - /srv:/srv
    userns_mode: keep-id
    environment:
      TZ: Etc/UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767/api/v1/ping"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # TvShow & Movie requests
  jellyseerr:
    image: docker.io/seerr/seerr:v3.3.0
    restart: unless-stopped
    network_mode: pasta
    ports:
      - 5055:5055    # web UI
    volumes:
      - jellyseerr-config:/app/config
    userns_mode: keep-id
    environment:
      TZ: Etc/UTC
      PORT: 5055
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5055/api/v1/settings/public"]
      start_period: 20s
      start_interval: 15s
      interval: 15s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

x-podman:
  in_pod: false