---
container_user: "{{ ansible_user }}"

common_compose_base_dir: "/home/{{ container_user }}/.local/share/containers"
common_user_systemd_dir: "/home/{{ container_user }}/.config/systemd/user"
common_user_bin_dir: "/home/{{ container_user }}/.local/bin"

# ---------------------------------------------------------------------------
# MariaDB
# ---------------------------------------------------------------------------
database_mariadb_root_password: "{{ lookup('viczem.keepass.keepass', 'ubuntu_database/mariadb_root_password', 'password') }}"

# ---------------------------------------------------------------------------
# Redis
# ---------------------------------------------------------------------------
database_redis_nextcloud_password: "{{ lookup('viczem.keepass.keepass', 'shared/redis_nextcloud_password', 'password') }}"
database_redis_onlyoffice_password: "{{ lookup('viczem.keepass.keepass', 'shared/redis_onlyoffice_password', 'password') }}"

# ---------------------------------------------------------------------------
# RabbitMQ
# ---------------------------------------------------------------------------
database_rabbitmq_default_user: "admin"
database_rabbitmq_default_password: "{{ lookup('viczem.keepass.keepass', 'shared/rabbitmq_default_password', 'password') }}"
