version: '3'

services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:4.0.0
    container_name: ddclient
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./ddclient.conf:/config/ddclient.conf
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 16M
